### ISSUE TITLE
Extracting Wikipedia Text

### ISSUE THREAD

**Issue by conceptofmind** [spencermountain/dumpster-dip#4] opened 2023-12-20 04:02 UTC
Hello,

Thank you for your awesome work in relation to dumpster-dive and dumpster-dip.

When running text extraction on enwiki:
```javascript
import dip from 'dumpster-dip'

const opts = {
  input: "./enwiki-latest-pages-articles.xml",
  // directory for all our new files
  outputDir: './enwiki/',
  // how we should write the results
  outputMode: 'flat',

  // which wikipedia namespaces to handle (null will do all)
  namespace: 0, //(default article namespace)
  // define how many concurrent workers to run
  //interval to log status
  heartbeat: 5000, //every 5 seconds
  
  // parse redirects, too
  redirects: false, // (default)
  // parse disambiguation pages, too
  disambiguation: true, // (default)

  // allow a custom wtf_wikipedia parsing library
  libPath: 'wtf_wikipedia', // (default)

  // should we skip this page or return something?
  doPage: function(doc){ return true}, // (default)

  // what do return, for every page
  parse: function(doc){return doc.json()}, // (default)  - avoid using an arrow-function

}

// this promise takes ~4hrs
dip(opts).then(() => {
  console.log('done!')
})
```
I am getting this error:
```
Error: ENAMETOOLONG: name too long, open '/wikipedia/enwiki/Protocol_Amending_the_Agreements%2C_Conventions_and_Protocols_on_Narcotic_Drugs_concluded_at_The_Hague_on_23_January_1912%2C_at_Geneva_on_11_February_1925_and_19_February_1925%2C_and_13_July_1931%2C_at_Bangkok_on_27_November_1931_and_at_Geneva_on_26_June_1936.txt'
    at Object.openSync (node:fs:590:3)
    at Object.writeFileSync (node:fs:2202:35)
    at writeFile (file:///home/henry/node_modules/dumpster-dip/src/output/index.js:20:6)
    at output (file:///home/henry/node_modules/dumpster-dip/src/output/index.js:37:5)
    at eachPage (file:///home/henry/node_modules/dumpster-dip/src/worker/index.js:64:5)
    at SundayDriver.each (file:///home/henry/node_modules/dumpster-dip/src/worker/01-reader.js:18:7)
    at SundayDriver.doChunk (/home/henry/node_modules/sunday-driver/src/index.js:38:8)
    at doit (/home/henry/node_modules/sunday-driver/src/index.js:77:10)
    at /home/henry/node_modules/sunday-driver/src/index.js:80:9
    at /home/henry/node_modules/sunday-driver/src/index.js:41:5 {
  errno: -36,
  syscall: 'open',
  code: 'ENAMETOOLONG',
  path: '/wikipedia/enwiki/Protocol_Amending_the_Agreements%2C_Conventions_and_Protocols_on_Narcotic_Drugs_concluded_at_The_Hague_on_23_January_1912%2C_at_Geneva_on_11_February_1925_and_19_February_1925%2C_and_13_July_1931%2C_at_Bangkok_on_27_November_1931_and_at_Geneva_on_26_June_1936.txt'
}
```
I am wondering if you have any input on why this would occur?

Also whether `doc.json()` or only `doc.text()` should be used to extract all of the page text.

**Comment by spencermountain** [comment] 2023-12-20 14:24
hahaha, that's awesome.
what operating system are you on? they all have different rules about this.
i can put a if statement that skips these long filenames, with some kinda flag in the config.

For now, you can add a your own filter, like:
```js
doPage: function(doc){ return doc.title().length<500},
```
Good catch!

**Comment by spencermountain** [comment] 2023-12-20 15:16
yeah, I'll add a default-on skip for anything > 255 characters, via [this](https://en.m.wikipedia.org/wiki/Comparison_of_file_systems#Limits).
cheers

**Comment by conceptofmind** [comment] 2023-12-20 17:30
> hahaha, that's awesome. what operating system are you on? they all have different rules about this. i can put a if statement that skips these long filenames, with some kinda flag in the config.
> 
> For now, you can add a your own filter, like:
> 
> ```js
> doPage: function(doc){ return doc.title().length<500},
> ```
> 
> Good catch!

Hi @spencermountain,

Thank you for the response.

I am using Ubuntu 18 as my operating system and nvm 16.

When running the script above on the Wikipedia XML files, they will start extracting but after numerous hours last night, they did not finish.

The outputs will look like this in the terminal:
```
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
 604,692    337,024     75,830     96,733     37,321      2,170      6,970    361,617     52,239     21,972     36,386     38,809
```
But it seems to freeze after a certain amount of time. Around 1.695 million txt files were processed.

I greatly appreciate all of your help!

**Comment by spencermountain** [comment] 2023-12-22 15:04
i reproduced this on a old linux box last night. Will take a look at what's going on.
thanks

**Comment by conceptofmind** [comment] 2023-12-23 03:57
I appreciate the help!

The only other thing to mention is upon manual analysis it seems like some edge cases may be slipping through in relation to wtf Wikipedia.
```
Die 3de Dinastie van Antieke Egipte (ook Dinastie III geskryf) was die eerste dinastie van die Ou Ryk. Dit het geduur van omstreeks 2667 tot 2610 v.C. Dit het gevolg op die onstuimige jare van die 2de Dinastie.

Die 4de, 5de en 6de Dinastie word gewoonlik saam met die 3de Dinastie die Ou Ryk genoem, ook bekend as die tyd van die piramides. Die hoofstad in dié tyd was Memphis.

Die bekendste heersers van die 3de Dinastie was:

! scope=col width="15%" | Farao ! scope=col width="20%" | Troonnaam ! scope=col width="20%" | Bewind ! scope=col width="15%" | Hoofstad ! scope=col width="35%" | Graftombe
 * Djoser
 * Netjerichet
 * 2667-2648 v.C.
 * Memphis
 * Saqqara
 * Djoserty
 * Sechemchet
 * 2648-2640 v.C.
 * Memphis
 * Saqqara
 * Nebka
 * Sanacht
 * 2640-2631 v.C.
 * Memphis
 * Abydos ?
 * Teti
 * Chaba
 * 2631-2628 v.C.
 * Memphis
 * Zawjet el-Arjan
 * Hoeni
 * Qahedjet ?
 * 2628-2610 v.C.
 * Memphis
 * Meidoem ?
 * }
 * Qahedjet ?
 * 2628-2610 v.C.
 * Memphis
 * Meidoem ?
 * }
 ```
I just wanted to confirm that this is right way to extract the text from the pages:
```javascript
libPath: 'wtf_wikipedia', // (default)

doPage: function(doc){ return true}, // (default)

parse: function(doc){return doc.text()}, 
```
Thank you,

Enrico

**Comment by spencermountain** [comment] 2023-12-27 23:00
hey Enrico, got a fix for both of these on dev, should have a release in the next few days
cheers

**Comment by spencermountain** [comment] 2023-12-28 20:48
both should be fixed now, in `2.0.0`
cheers!

**Closed as completed by spencermountain** 2023-12-28 20:48 UTC
Labels: enhancement, next-release

**Comment by s-jse** [comment] 2024-02-27 01:07
What was the reason for the freeze? I'm running into the same issue on version `2.0.0` when processing the latest dump of English Wikipedia. It freezes after writing ~6.2 million articles to the output.

This is my main script:

```
import dip from 'dumpster-dip'

const opts = {
    input: './workdir/en/wikipedia_02_21_2024/latest-pages-articles-multistream.xml',
    outputDir: './workdir/results',
    outputMode: 'encyclopedia-two',
    libPath: './wikiparser/_lib.js',
    heartbeat: 5000, //every 5 seconds

    namespace: 0, //(default article namespace)
    redirects: false,
    disambiguation: false,

    doPage: function (doc) {
        return true
    },

    parse: function (doc) {
        let ret = doc.json()
        ret["markdown"] = doc.markdown()
        ret["html"] = doc.html()
        ret["text"] = doc.text()

        if (Array.isArray(ret["sections"])) {
            // Iterate over each section
            ret["sections"].forEach(section => {
                // Remove the "images" field from the section
                delete section["images"];
            });
        }
        return ret
    }
}

dip(opts).then(() => {
    console.log('done!')
})
```

**Comment by s-jse** [comment] 2024-02-27 04:14
And the same issue with the length of file names:

```
Worker 23 couldn't process 'Cneoridium dumosum (Nuttall) Hooker F. Collected March 26, 1960, at an Elevation of about 1450 Meters on Cerro Quemazón, 15 Miles South of Bahía de Los Angeles, Baja California, México, Apparently for a Southeastward Range Extension of Some 140 Miles.':
 got error Error: ENAMETOOLONG: name too long, open 'workdir/results/cn/Cneoridium_dumosum_(Nuttall)_Hooker_F._Collected_March_26%2C_1960%2C_at_an_Elevation_of_about_1450_Meters_on_Cerro_Quemaz%C3%B3n%2C_15_Miles_South_of_Bah%C3%ADa_de_Los_Angeles%2C_Baja_California%2C_M%C3%A9xico%2C_Apparently_for_a_Southeastward_Range_Exte.txt
```
